# about.toml


accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "Zlib",
    "Unlicense",
    "AGPL-3.0",
    "CC0-1.0",     
    "ISC",          
    "NCSA",         
    "Unicode-3.0",  
    "LGPL-2.1",     
]

